# =====================================================================
# Alpment OS 1 - Flatpak Depo ve Kaynak Yönetim Yapılandırması
# =====================================================================

[Flathub-Main]
Url=https://dl.flathub.org/repo/flathub.flatpakrepo
Title=Flathub Stable Repository
GPGKey=https://dl.flathub.org/repo/flathub.gpg
Enabled=true
Priority=1

[Flathub-Beta]
Url=https://dl.flathub.org/beta-repo/flathub-beta.flatpakrepo
Title=Flathub Beta Repository
GPGKey=https://dl.flathub.org/beta-repo/flathub-beta.gpg
# Kararlılık için varsayılan olarak kapalı, kullanıcı isterse ayarlardan açabilir
Enabled=false
Priority=10
