#!/usr/bin/env bash
# Generated by Alpment OS Builder - 2026
# =====================================================================
# Alpment OS 1 - Ana Kimlik ve ISO Yapılandırma Dosyası
# =====================================================================

iso_name="Alpment-OS"
iso_label="ALPMENT_OS_1"
iso_publisher="Alpment OS Developer <https://github.com/secretmantyt31-cyber>"
iso_application="Alpment OS 1 Live/Installation Media"
iso_version="1.0"
install_dir="arch"
buildmodes=('iso')
bootmodes=('bios.syslinux.mbr' 'bios.syslinux.eltorito'
          'uefi-ia32.grub.esp' 'uefi-x64.grub.esp'
          'uefi-ia32.grub.eltorito' 'uefi-x64.grub.eltorito')
arch="x86_64"
pacman_conf="pacman.conf"

# =====================================================================
# Dosya ve Klasör İzinleri (Hatasız Sistem Çalışması İçin Güvenlik Ayarları)
# =====================================================================
file_permissions=(
  ["/etc/shadow"]="0:0:400"
  ["/etc/gshadow"]="0:0:400"
  ["/etc/passwd"]="0:0:644"
  ["/etc/group"]="0:0:644"
  ["/etc/sudoers"]="0:0:440"
  ["/root"]="0:0:750"
  ["/root/.automated_script.sh"]="0:0:755"
  ["/usr/local/bin/choose-mirror"]="0:0:755"
  ["/usr/local/bin/Installation_guide"]="0:0:755"
  ["/usr/local/bin/livecd-sound"]="0:0:755"
)
