name: Alpment OS 1 ISO Builder

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged

    steps:
    - name: Sistemi Güncelle ve Gerekli Araçları Kur
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm git archiso grub libisoburn mtools squashfs-tools

    - name: Proje Dosyalarını Çek
      uses: actions/checkout@v4

    - name: Resmi Archiso Profilini Al ve Alpment İçin Hazırla
      run: |
        mkdir -p /tmp/archiso-workspace
        # Arch Linux'un resmi eksiksiz profilini çalışma alanına kopyalıyoruz
        cp -r /usr/share/archiso/configs/releng /tmp/archiso-workspace/alpment_profile
        
        # Eğer senin depoda kendi özelleştirmelerin varsa üstüne yazar, yoksa resmi dosyalar kalır
        if [ -d "archiso" ]; then
          cp -r archiso/* /tmp/archiso-workspace/alpment_profile/
        fi

    - name: Alpment OS ISO Derleme İşlemini Başlat
      run: |
        cd /tmp/archiso-workspace
        mkarchiso -v -w work_dir -o out_dir alpment_profile

    - name: Derlenen ISO Dosyasını GitHub'a Yükle
      uses: actions/upload-artifact@v4
      with:
        name: Alpment-OS-1-ISO
        path: /tmp/archiso-workspace/out_dir/*.iso
        if-no-files-found: error
        retention-days: 7
